import type { V2Dictionary } from "./types";

export const v2ca: V2Dictionary = {
  meta: {
    title: "Kairox — Producció publicitària amb IA per a marques",
    description:
      "Generem imatge, vídeo i contingut per a xarxes a la velocitat i al cost de la IA. Per a marques que no es poden permetre esperar quatre setmanes per un spot.",
  },
  nav: {
    services: "Serveis",
    sectors: "Sectors",
    process: "Procés",
    contact: "Contacte",
    cta: "Parlem",
  },
  hero: {
    eyebrow: "studio · producció · ia",
    headline: "La teva propera campanya, ",
    headlineTail: "sense la productora.",
    subhead:
      "Generem imatge, vídeo i contingut per a xarxes amb IA — a una fracció del cost d'una productora tradicional i en dies, no en setmanes. Per a marques que necessiten iterar ràpid i aparèixer a tot arreu alhora.",
    cta: "Parlem",
    secondaryCta: "Veure serveis",
    badges: ["Imatge", "Vídeo", "Reels diaris", "DTC · Ecommerce"],
  },
  studioVisual: {
    app: "kairox · studio render queue",
    live: "rendering",
    queueLabel: "cua de renderitzat",
    variantLabel: "variants",
    statusReady: "llest",
    statusRendering: "rendering",
    statusQueued: "en cua",
  },
  servicesSection: {
    eyebrow: "què produïm",
    title: "Tres línies, un objectiu: que la teva marca tingui el contingut que necessita, quan el necessita.",
    body: "Hem productitzat el que abans era un projecte a mida amb pressupost tancat. Tu ens dius què necessites; nosaltres entreguem.",
    seeAll: "Veure serveis complets",
    pricingNote: "Cotització a mida segons marca, volum i exclusivitat.",
  },
  services: [
    {
      slug: "imagenes",
      name: "Packs d'imatge per producte",
      short: "Catàleg, lifestyle i campanya — generats sobre el teu producte, llestos per a web, ecommerce i xarxes.",
      description: "Imatge estàtica a mida: variants de catàleg, escenes lifestyle, angles de càmera, fons i composicions. Entregat en els formats que necessites (quadrat, vertical, horitzontal, banner). Pensat per a marques DTC que renoven creativitats constantment.",
      unit: "per nombre de productes",
      sampleAlt: "Mostres d'imatge generades per a diferents productes",
      tiers: [
        { slug: "1-producto", label: "1 producte", headline: "Setup mínim, ideal per a una primera prova", description: "Un únic producte, diverses escenes i formats.", bullets: ["Fins a 20 variants per producte", "3 escenaris (catàleg, lifestyle, campanya)", "Formats: quadrat, vertical, horitzontal", "Lliurament en 5 dies laborables"] },
        { slug: "2-productos", label: "2 productes", headline: "Per a marques que llancen en parelles", description: "Dos productes coordinats visualment.", bullets: ["Fins a 20 variants per producte", "Coherència visual entre tots dos productes", "Formats estesos per a campanyes multi-canal", "Lliurament en 7 dies laborables"] },
        { slug: "3-productos", label: "3 productes", headline: "Per a col·leccions i llançaments complets", description: "Tres productes com una col·lecció coherent.", bullets: ["Fins a 20 variants per producte", "Hero shots + escenes de grup", "Variants específiques per canal", "Lliurament en 10 dies laborables"] },
      ],
    },
    {
      slug: "video",
      name: "Packs de vídeo per durada",
      short: "Des d'un story de 5 segons fins a un spot de 60. Mateix procés, format diferent.",
      description: "Vídeo generat o produït amb IA, amb el teu producte, la teva marca i el teu missatge. Cobrim des de stories i reels de xarxes socials fins a spots per a web, presentacions i campanyes pagades.",
      unit: "per durada",
      sampleAlt: "Mostres de fotogrames de vídeos generats",
      tiers: [
        { slug: "5s", label: "5 segons", headline: "Stories i bumpers", description: "Peça curta per a stories, pre-roll, transicions.", bullets: ["Fins a 5 variants", "Vertical i quadrat", "Lliurament en 3 dies"] },
        { slug: "15s", label: "10–15 segons", headline: "Reels i posts de feed", description: "Format dominant a TikTok, IG, Reels.", bullets: ["Fins a 4 variants", "Optimitzat per plataforma", "Lliurament en 4 dies"] },
        { slug: "30s", label: "20–30 segons", headline: "Spots curts per a xarxes i web", description: "Per a campanyes pagades i home de web.", bullets: ["Fins a 3 variants amb focus diferent", "Veu en off i subtítols opcionals", "Lliurament en 6 dies"] },
        { slug: "60s", label: "60 segons", headline: "Spots complets", description: "Peça amb narrativa per a campanyes.", bullets: ["Fins a 2 variants", "Storyboard previ, veu en off, música", "Lliurament en 10 dies"] },
        { slug: "120s", label: "1–2 minuts", headline: "Branded content", description: "Peça estesa per a web, presentacions, vídeo corporatiu.", bullets: ["Storyboard + script treballat", "Múltiples escenes i locucions", "Lliurament en 14 dies"] },
      ],
    },
    {
      slug: "suscripcion",
      name: "Subscripció de contingut per a xarxes",
      short: "Un flux constant de reels diaris llestos per publicar. Sense forats al teu calendari.",
      description: "Contingut continu per mantenir la teva marca present a xarxes sense que un equip intern hagi de produir-lo. Adaptació nativa per plataforma — un mateix concepte en variants per a Instagram, TikTok, Facebook i X.",
      unit: "per mes",
      sampleAlt: "Mostres de reels publicats a xarxes socials",
      tiers: [
        { slug: "1-reel", label: "1 reel diari", headline: "Presència constant", description: "Un reel cada dia laborable, llest per publicar.", bullets: ["20–22 reels al mes", "Adaptat a IG, TikTok, FB, X", "Calendari editorial mensual", "Iteració mensual sobre rendiment"] },
        { slug: "2-reels", label: "2 reels diaris", headline: "Per a marques amb apetit alt de publicació", description: "Doble cadència per alimentar diverses plataformes.", bullets: ["40–44 reels al mes", "Variants específiques per canal", "Anàlisi mensual de rendiment", "Línia editorial co-treballada"] },
        { slug: "3-reels", label: "3 reels diaris", headline: "Per a marques always-on", description: "Triple cadència amb A/B continu.", bullets: ["60–66 reels al mes", "A/B sobre formats i missatges", "Reporting setmanal", "Roadmap de contingut trimestral"] },
      ],
    },
  ],
  sectorsSection: {
    eyebrow: "per a qui",
    title: "Marques que necessiten velocitat i volum sense perdre qualitat.",
    body: "Treballem especialment bé amb marques DTC i ecommerce que renoven creativitats constantment. Si la teva producció tradicional costa quatre setmanes i cinc mil euros per spot, parlem.",
    seeAll: "Veure tots els sectors",
  },
  sectors: [
    { slug: "puericultura", name: "Puericultura i infantil", short: "Producte físic amb vida útil de campanya curta i alta rotació de creativitats.", description: "Marques com les que hi ha a qualsevol fira del sector — Jané, Asalvo, Babyauto, Olmitos, Lorena Canals — necessiten renovar contingut per a cada llançament i cada canal. Utilitzem el teu producte real com a referència i generem les escenes que necessites.", uses: ["Imatge de catàleg i lifestyle per SKU", "Reels diaris per a Instagram i TikTok", "Spots de 15–30s per a campanyes estacionals"], imageAlt: "Producte de puericultura en una escena lifestyle" },
    { slug: "cosmetica", name: "Cosmètica i cura personal", short: "Llançaments freqüents, packaging que importa, comunitat activa a xarxes.", description: "Marques com Freshly Cosmetics, ISDIN o qualsevol marca DTC del sector cosmètic viuen de llançaments i de presència constant. Generem packshots, vídeos de producte, reels d'ús i campanyes estacionals.", uses: ["Packshots i bodegons per producte", "Vídeo d'aplicació / textura", "Calendari de reels per a llançaments"], imageAlt: "Bodegó de producte cosmètic amb llum natural" },
    { slug: "moda", name: "Moda i accessoris", short: "Col·leccions per temporada, look-and-feel coherent, molt contingut per a molts canals.", description: "Marques com Singularu, Gocco o qualsevol marca de moda DTC necessiten generar contingut a velocitat de col·lecció. Treballem sobre les teves peces reals per mantenir fidelitat de producte.", uses: ["Look-books generats per col·lecció", "Variants per model i per canal", "Vídeo editorial curt"], imageAlt: "Peça de moda fotografiada a estudi" },
    { slug: "hogar", name: "Llar i decoració", short: "Producte que necessita veure's en context. Molta varietat d'escenes i ambients.", description: "Per a marques de llar, decoració i moble, la imatge lifestyle ven més que el packshot. Generem escenes de producte en diferents ambients — modern, mediterrani, nòrdic — sense haver de muntar set.", uses: ["Lifestyle per ambient", "Variants estacionals (Nadal, primavera)", "Reels d'ús i inspiració"], imageAlt: "Producte de llar en una escena de saló" },
    { slug: "dtc-ecommerce", name: "DTC i ecommerce", short: "Volum constant, pressupost acotat, KPIs de conversió clars.", description: "Si vens online i el teu motor són les creativitats, necessites iterar contínuament. Et donem un flux regular d'imatge, vídeo i reel — i ens integrem amb el teu equip de performance per alimentar campanyes pagades amb material fresc.", uses: ["Creativitats per a Meta Ads i TikTok Ads", "Variants A/B sobre el mateix producte", "Reels i posts orgànics diaris"], imageAlt: "Marca DTC a la seva botiga online" },
    { slug: "servicios", name: "Marques de serveis", short: "Sense producte físic — la creativitat es recolza en el concepte i el storytelling.", description: "Per a marques de serveis (B2B, SaaS, consultoria, salut, educació), la peça no és el producte: és la idea. Generem contingut conceptual, escenes humanes, gràfics animats i vídeo explicatiu.", uses: ["Vídeo explicatiu de producte / servei", "Reels editorials conceptuals", "Imatge per a landing i campanyes"], imageAlt: "Escena d'oficina moderna amb persones treballant" },
  ],
  comparisonSection: {
    eyebrow: "per què amb nosaltres",
    title: "El mateix que una productora — sense el que fa que costi quatre setmanes.",
    body: "No anem contra l'ofici del cinema ni de la publicitat. Anem contra el cost i el temps que la majoria de marques no es poden permetre mes a mes.",
    leftLabel: "Producció tradicional",
    rightLabel: "Producció amb Kairox",
    rows: [
      { metric: "Temps mitjà per spot", traditional: "3–6 setmanes", kairox: "3–10 dies", delta: "10× més ràpid" },
      { metric: "Cost per spot 15s", traditional: "3.000 – 8.000 €", kairox: "200 – 500 €", delta: "Fins a 15× menys cost" },
      { metric: "Variants per concepte", traditional: "1 final", kairox: "5–8 variants", delta: "Més material per A/B" },
      { metric: "Iteracions després de revisió", traditional: "1–2 limitades", kairox: "Les que necessitis", delta: "Sense sobrecostos ocults" },
      { metric: "Rotació de creativitats", traditional: "Trimestral", kairox: "Setmanal o diària", delta: "Per a campanyes always-on" },
    ],
  },
  processSection: {
    eyebrow: "com treballem",
    title: "Cinc passos. Sense reunions de quatre hores. Sense canvis sorpresa de pressupost.",
    body: "Pensat perquè el teu equip de marketing rebi contingut sense haver-se de convertir en productors.",
    steps: [
      { label: "01", title: "Brief", body: "Producte, marca, angles, to. En una trucada de 30 minuts tanquem l'abast.", detail: "Necessitem entendre el teu producte, els teus claims, la teva identitat visual i els angles comercials que vols explorar. Si tens un brand kit, brief de campanya o referències visuals, millor — però no és bloquejant." },
      { label: "02", title: "Generació", body: "Generem les primeres variants en 48–72 hores. Tu les revises en una galeria privada.", detail: "Treballem en paral·lel amb diversos models i tècniques. Cada concepte surt en múltiples variants per comparar. Accés a una galeria privada on marques quines vols iterar i quines descartes." },
      { label: "03", title: "Review", body: "Iterem sobre el teu feedback. Sense límit de retocs dins l'abast.", detail: "Cada iteració baixa l'entropia: del 'm'agrada aquesta direcció però més net' al 'això val'. No cobrem extra per iteracions raonables — està inclòs a l'abast." },
      { label: "04", title: "Lliurament", body: "Lliurem en els formats que necessitis — quadrat, vertical, horitzontal, banner — llestos per publicar.", detail: "Cada peça es lliura en els formats que el teu equip de marketing necessita: xarxes (quadrat, vertical), web (banner, hero), ads (quadrat i vertical), email (horitzontal). Naming clar, organització per carpeta, tot descarregable." },
      { label: "05", title: "Iteració", body: "Per a subscripcions: revisem rendiment mes a mes i ajustem el roadmap de contingut.", detail: "En contractes de subscripció mensual, avaluem quines peces estan funcionant (impressions, engagement, CTR si ho mesurem junts) i orientem la següent tanda cap a angles que estan donant resultat." },
    ],
    needs: { title: "Què necessitem de tu", items: ["El teu producte (físic o referències clares)", "Brand kit o guia d'estil (si la tens)", "Una persona de contacte que pugui decidir i donar feedback", "Accés als teus canals per entendre to i audiència (opcional)"] },
  },
  finalCta: {
    title: "La teva propera campanya comença ja?",
    body: "Explica'ns quina marca portes i què necessites. Et responem en 24 hores amb proposta concreta.",
    cta: "Parlem",
  },
  contact: {
    eyebrow: "contacte",
    title: "Explica'ns la teva marca i la teva propera campanya.",
    body: "Responem en menys de 24 hores laborables amb una proposta concreta i un calendari realista.",
    formName: "Nom",
    formCompany: "Marca / empresa",
    formEmail: "Email",
    formMessage: "Explica'ns quin tipus de contingut necessites",
    formConsent: "He llegit i accepto la {privacy}. Dono el meu consentiment perquè Kairox tracti les meves dades per respondre a aquesta consulta.",
    formConsentRequired: "Has d'acceptar la política de privacitat.",
    formSubmit: "Enviar",
    formSubmitting: "Enviant…",
    formSuccess: "Missatge rebut. Et responem en menys de 24 hores.",
    formError: "Alguna cosa ha fallat. Escriu-nos directament a {email}.",
    emailLabel: "Escriu-nos directament",
    privacyLink: "política de privacitat",
  },
  footer: {
    tagline: "Producció publicitària amb IA per a marques que no poden esperar.",
    nav: "Navegació",
    legal: "Legal",
    avisoLegal: "Avís legal",
    privacidad: "Privacitat",
    cookies: "Cookies",
    rights: "Tots els drets reservats.",
    versionSwitch: "← Veure Kairox v1 (back office)",
  },
};
